version: '3'

vars:
  alpinejs_version: "3.13.5"
  htmx_version: "1.9.12"
  name: "podium"

includes:
  golang:
    taskfile: https://raw.githubusercontent.com/soltiHQ/actions/main/taskfiles/go/Taskfile.yml
    vars:
      image_patch: "-1"
  helpers:
    taskfile: https://raw.githubusercontent.com/soltiHQ/actions/main/taskfiles/helpers/Taskfile.yml

tasks:
  _proto/vendor:
    desc: Vendor proto from soltiHQ/proto.
    internal: true
    silent: true
    cmds:
      - task: helpers:proto/vendor
        vars:
          proto_ref: "v0.0.1"
          MAPPINGS: |
            solti/discover api/proto/solti/discover
            solti/task api/proto/solti/task
            solti/raft api/proto/solti/raft

  _deps:
    desc: Install dependencies.
    internal: true
    silent: true
    cmds:
      - task: helpers:download/file
        vars:
          URL: "https://cdn.jsdelivr.net/npm/alpinejs@{{.alpinejs_version}}/dist/cdn.min.js"
          TO: "ui/static/js/alpine.min.js"
      - task: helpers:download/file
        vars:
          URL: "https://unpkg.com/htmx.org@{{.htmx_version}}/dist/htmx.min.js"
          TO: "ui/static/js/htmx.min.js"

  prepare:
    desc: Prepare sources.
    cmds:
      - task: _proto/vendor
      - task: _deps

      - task: golang:proto
      - task: golang:templ
      - task: golang:tailwindcss
        vars:
          INPUT: "ui/static/css/app.css"
          OUTPUT: "ui/static/css/tailwindcss.css"

      - task: golang:tidy
      - task: golang:vendor

  ci/fumpt:
    desc: Run gofumpt.
    cmds:
      - task: golang:gofumpt

  ci/lint:
    desc: Run golangci-lint.
    cmds:
      - task: golang:golangci

  ci/test:
    desc: Run go test.
    cmds:
      - task: golang:test

  ci/vulnerability:
    desc: Run govulncheck.
    cmds:
      - task: golang:govulncheck

  ci/vendor:
    desc: Prepare sources.
    cmds:
      - task: prepare

  ci/build:
    desc: Build binary.
    vars:
      GOOS:   '{{.GOOS | default "linux"}}'
      GOARCH: '{{.GOARCH | default "amd64"}}'
    cmds:
      - task: golang:build
        vars:
          NAME: "{{.name}}"
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.GOARCH}}"
