name: Go Cache

outputs:
  cache-hit:
    description: "'true' if an exact cache key match was found."
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - id: cache
      uses: actions/cache@v5
      with:
        path: |
          .cache
          vendor
          api/gen
          ui/static
          ui/templates
        key: podium-${{ hashFiles('go.mod', 'go.sum', 'Taskfile.yaml', 'buf.yaml', 'buf.gen.yaml', 'tailwind.config.cjs', 'ui/static/css/app.css', 'ui/**/*.templ') }}
