name: Build

on:
  workflow_call: {}

jobs:
  build:
    runs-on: ${{ vars.RUNS_ON }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: arm64

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/go-cache
      - name: Build ${{ matrix.goos }}/${{ matrix.goarch }}
        uses: soltiHQ/actions/taskfile@main
        with:
          command: ci/build GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}
